"""Markdown -> .docx conversion for Gemini-generated drafts.

Our drafts are produced against a fixed skeleton in `backend/llm/prompts.py`, so
the Markdown they emit is predictable:
- `# Title`                    -> Heading 1 (Title)
- `## N. Section`              -> Heading 2
- `**Label:** value`           -> metadata paragraph with bold label
- `N. text` / `- text`         -> numbered / bulleted lists
- `[source: doc_id]`           -> inline italic citation
- blank line                   -> paragraph break

Rather than pull in a full Markdown parser, we walk the lines ourselves: the
output space is small and the parser is easy to keep correct.
"""
from __future__ import annotations

import io
import re
from datetime import date

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_LINE_SPACING
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor, Cm

# ---------------------------------------------------------------------------
# Regex primitives
# ---------------------------------------------------------------------------

_H1 = re.compile(r"^#\s+(.+)$")
_H2 = re.compile(r"^##\s+(.+)$")
_H3 = re.compile(r"^###\s+(.+)$")
_NUMBERED = re.compile(r"^(\d+)\.\s+(.+)$")
_BULLETED = re.compile(r"^[-*]\s+(.+)$")
_BOLD_FIELD = re.compile(r"^\*\*(.+?):\*\*\s*(.*)$")

# Inline markers: **bold**, *italic*, `code`, [source: doc_id]
_INLINE_SEG = re.compile(
    r"(\*\*[^*]+\*\*|"                # bold
    r"\*[^*]+\*|"                     # italic
    r"`[^`]+`|"                       # code
    r"\[source:\s*[^\]]+\])"         # source citation
)


def _configure_styles(doc: Document) -> None:
    """QCI-branded defaults: Inter-ish sans-serif, sensible margins, accent colour."""
    # Base style
    base = doc.styles["Normal"]
    base_font = base.font
    base_font.name = "Calibri"  # widely available on Windows; safe fallback
    base_font.size = Pt(11)
    base.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
    base.paragraph_format.line_spacing = 1.15
    base.paragraph_format.space_after = Pt(6)

    # Force east-asia font to match (docx quirk)
    rPr = base.element.get_or_add_rPr()
    rFonts = rPr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = rPr.makeelement(qn("w:rFonts"), {})
        rPr.append(rFonts)
    rFonts.set(qn("w:ascii"), "Calibri")
    rFonts.set(qn("w:hAnsi"), "Calibri")

    for level, pt in ((1, 20), (2, 14), (3, 12)):
        style = doc.styles[f"Heading {level}"]
        style.font.name = "Calibri"
        style.font.size = Pt(pt)
        style.font.bold = True
        style.font.color.rgb = RGBColor(0x1A, 0x38, 0x71)  # QCI navy-ish
        style.paragraph_format.space_before = Pt(14 if level == 1 else 10)
        style.paragraph_format.space_after = Pt(4)

    # Margins
    for section in doc.sections:
        section.top_margin = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin = Cm(2.2)
        section.right_margin = Cm(2.2)


def _add_runs(paragraph, text: str) -> None:
    """Inline formatting: **bold**, *italic*, `code`, [source: ...] italic."""
    if not text:
        return
    for segment in _INLINE_SEG.split(text):
        if not segment:
            continue
        if segment.startswith("**") and segment.endswith("**"):
            run = paragraph.add_run(segment[2:-2])
            run.bold = True
        elif segment.startswith("*") and segment.endswith("*") and len(segment) > 2:
            run = paragraph.add_run(segment[1:-1])
            run.italic = True
        elif segment.startswith("`") and segment.endswith("`"):
            run = paragraph.add_run(segment[1:-1])
            run.font.name = "Consolas"
        elif segment.startswith("[source:") and segment.endswith("]"):
            # Render as italic + accent colour so citations visually "chip"
            run = paragraph.add_run(segment)
            run.italic = True
            run.font.color.rgb = RGBColor(0x1A, 0x38, 0x71)
        else:
            paragraph.add_run(segment)


def markdown_to_docx(markdown: str, *, filename_hint: str = "qci-draft") -> bytes:
    """Render `markdown` as a QCI-branded .docx; returns the bytes (ready to stream)."""
    doc = Document()
    _configure_styles(doc)

    # Header strip: QCI identifier at top of every page
    header_p = doc.sections[0].header.paragraphs[0]
    header_run = header_p.add_run("Quality Council of India  |  Project Planning and Implementation Division")
    header_run.font.size = Pt(9)
    header_run.font.color.rgb = RGBColor(0x6B, 0x6B, 0x6B)

    # Footer: generated-on timestamp
    footer_p = doc.sections[0].footer.paragraphs[0]
    footer_run = footer_p.add_run(f"Generated by Central Finite Curve · {date.today().isoformat()}")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0x6B, 0x6B, 0x6B)

    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            # blank line: let docx natural spacing handle the gap
            continue

        if (m := _H1.match(line)):
            p = doc.add_heading(level=1)
            _add_runs(p, m.group(1))
            continue
        if (m := _H2.match(line)):
            p = doc.add_heading(level=2)
            _add_runs(p, m.group(1))
            continue
        if (m := _H3.match(line)):
            p = doc.add_heading(level=3)
            _add_runs(p, m.group(1))
            continue
        if (m := _BOLD_FIELD.match(line)):
            p = doc.add_paragraph()
            run = p.add_run(f"{m.group(1)}: ")
            run.bold = True
            _add_runs(p, m.group(2))
            continue
        if (m := _NUMBERED.match(line)):
            p = doc.add_paragraph(style="List Number")
            _add_runs(p, m.group(2))
            continue
        if (m := _BULLETED.match(line)):
            p = doc.add_paragraph(style="List Bullet")
            _add_runs(p, m.group(1))
            continue

        p = doc.add_paragraph()
        _add_runs(p, line)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def safe_filename(hint: str) -> str:
    """Slug a doc_id / title into a filename-safe stub ending in .docx."""
    stub = re.sub(r"[^A-Za-z0-9_.-]+", "_", hint).strip("_") or "qci-draft"
    return f"{stub[:80]}.docx"
