"""Ensure corpus_chunks.embedding is a real pgvector column on Postgres.

The initial migration was autogenerated on SQLite where the embedding
column resolves to LargeBinary/bytea. On Postgres we need the actual
`vector(384)` type so pgvector operators (`<=>`) work.

This migration is a no-op on SQLite (the column stays bytea, still writable
via the JSON-serialize adapter in embeddings.py).

Safe to apply on prod even if corpus_chunks already has rows written under
the wrong type — we truncate before altering because the bytea bytes and
vector floats aren't interchangeable, and reingestion is idempotent.

Revision ID: 0002_pgvector
Revises: 30f5dad1bb64
Create Date: 2026-09-23
"""
from __future__ import annotations

from alembic import op

revision = "0002_pgvector"
down_revision = "30f5dad1bb64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Old rows (if any) are unusable — bytea bytes can't be cast to vector.
    op.execute("TRUNCATE TABLE corpus_chunks")
    op.execute("ALTER TABLE corpus_chunks DROP COLUMN IF EXISTS embedding")
    op.execute("ALTER TABLE corpus_chunks ADD COLUMN embedding vector(384)")


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("TRUNCATE TABLE corpus_chunks")
    op.execute("ALTER TABLE corpus_chunks DROP COLUMN IF EXISTS embedding")
    op.execute("ALTER TABLE corpus_chunks ADD COLUMN embedding bytea")
