"""initial cfc schema

Revision ID: 30f5dad1bb64
Revises: 
Create Date: 2026-09-23 16:44:00.277239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f5dad1bb64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('is_apex_scope', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('corpus_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('ministry', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('value_inr', sa.Float(), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=True),
    sa.Column('source_path', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('division_code', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['divisions.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id')
    )
    op.create_table('users',
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('cfc_role', sa.String(length=32), nullable=False),
    sa.Column('division_code', sa.String(length=32), nullable=True),
    sa.Column('manager_employee_id', sa.String(length=16), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['divisions.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['users.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_employee_id', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('division_code', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['users.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_code'], ['divisions.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_at', ['actor_employee_id', 'at'], unique=False)

    op.create_table('corpus_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_set', sa.JSON(), nullable=True),
    sa.Column('division_code', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['divisions.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['corpus_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_index')
    )
    with op.batch_alter_table('corpus_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_corpus_chunks_division', ['division_code'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('maker_employee_id', sa.String(length=16), nullable=False),
    sa.Column('division_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('submitted_version', sa.Integer(), nullable=True),
    sa.Column('final_storage_key', sa.String(length=400), nullable=True),
    sa.Column('final_sha256', sa.String(length=64), nullable=True),
    sa.Column('worker_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['divisions.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['maker_employee_id'], ['users.employee_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('actor_employee_id', sa.String(length=16), nullable=False),
    sa.Column('decided_on_version', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['users.employee_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('actor_employee_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['users.employee_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'version', name='uq_draft_version')
    )
    op.create_table('threads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('division_code', sa.String(length=32), nullable=False),
    sa.Column('anchor', sa.JSON(), nullable=True),
    sa.Column('body_snippet', sa.Text(), nullable=False),
    sa.Column('author_employee_id', sa.String(length=16), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_employee_id'], ['users.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_code'], ['divisions.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threads')
    op.drop_table('draft_versions')
    op.drop_table('draft_approvals')
    op.drop_table('drafts')
    with op.batch_alter_table('corpus_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_corpus_chunks_division')

    op.drop_table('corpus_chunks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_actor_at')

    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('corpus_documents')
    op.drop_table('divisions')
    # ### end Alembic commands ###
